### ISSUE TITLE
Implement From<[u8; $bytes]> for Hashes?

### ISSUE THREAD

**Issue by dongcarl** [rust-bitcoin/bitcoin_hashes#10]
See above.

**Comment by apoelstra** [comment]
Definitely needs discussion. I'd like to implement the rust-secp `ThirtyTwoByteHash` trait on these types at some point (this also needs discussion mainly because we need to decide what the dependency DAG around rust-bitcoin, bitcoin-hashes and rust-secp should be). But that trait assumes, among other things, that hashes are never all-bits-zero, which is not something we can enforce in `From<[u8; $bytes]>`.

**Comment by apoelstra** [comment]
We now have `from_inner` which accomplishes this. The ergonomics outweighed the anti-footgunness.
