### ISSUE TITLE
`hash` function ambiguous on Hash

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/bitcoin_hashes#113]
If you import both `std::hash::Hash` and `bitcoin_hashes::Hash`, then the various hash types (eg `sha256::Hash`) have two `hash` functions, making calls to it ambiguous. We had a user show up wondering why rustc was complaining that `hash` takes two arguments when it should take one, because rustc was using `std::hash::Hash` first.

**Comment by apoelstra** [comment]
duplicate of #16

**Comment by TheBlueMatt** [comment]
Not quite - #16 just talks about the actual trait names, which can be resolved with different `use` statements. Resolving this requires `<sha256::Hash as bitcoin_hashes::Hash>::hash()` instead of being able to call `sha256::Hash::hash()`.

**Comment by stevenroose** [comment]
I never found myself in the situation where I would have `std::hash::Hash` used often. Would it be too annoying to call `std::hash::Hash::hash(...)` with the full path? I mean duplicate method names are a feature of traits, right? I don't think we should be adopting more creative method names for that.

`use std::hash::Hash as StdHash;` could also help.

**Comment by TheBlueMatt** [comment]
In the particular user's case, I believe the call was defaulting to `std::hash::Hash` when they called `Sha256::hash()`. I'm not sure what the resolution rules are there - are they `use`-order-dependent? It seems pretty bad that just calling `Sha256::hash()` can default to `std::hash::Hash`, especially when, as you point out, you pretty rarely want that.

**Comment by stevenroose** [comment]
Hmm yeah I do agree that a silent default is definitely not what we want. Not even a "smart" default based on the function signature IMO. Any name collision should be explicitly resolved. Can you ask that user to check if that was surely the case? Because I think that might be reported as a rustc bug, or at least something up for improvement.

**Comment by TheBlueMatt** [comment]
I don't believe rustc ever resolves which function to call based on it's parameters, so it's not a rustc bug. Ultimately it's our bug - we have types which, using traits, have two methods with identical names. We should avoid that.

**Comment by Kixunil** [comment]
Rust definitely does error on ambiguous methods regardless of parameters. [Proof.](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0e7a0e43219638fc039b908fdb5c706d)

I can only imagine these cases for the user to experience what's described:

* One of the traits was not actually implemented (wrong type?) - most likely
* The user was mistaken in reporting or is lying.
* The user uses some Rust fork with that behavior changed (not serious)

I'm not convinced the whole world should rewrite the code just to fix weird edge cases like this. Especially since they don't affect correctness and may cause similar clash with something else. (If this was some UB or vulnerability I'd agree with a change.)

Also mixing the two traits *may* be an indication that the user is doing something wrong.

**Comment by TheBlueMatt** [comment]
> Rust definitely does error on ambiguous methods regardless of parameters. Proof.

Yes, that's exactly the point. I'm really not sure why this is at all unclear or something we have to debate.

The following code is completely sensible (something I've ~written in the past) and basically maximally obnoxious to have to write

```
use std::hash::Hash;
use bitcoin_hashes::Hash as OtherHash; // Why do I have to rename this, this sucks
use bitcoin_hashes::sha256::Hash as ThirdHash; // Ugh, seriously?

fn _do_things(object: ThirdHash) {
  object.hash(); // Rustc complains - this is ambiguous. Even with separate renamed imports this is ambiguous.
}
```

**Comment by Kixunil** [comment]
> The following code is completely sensible (something I've ~written in the past) and basically maximally obnoxious

Why would you need to manually work with anything from `std::hash::Hash`? It's either used in data structure (implementation of shouldn't need stuff from `bitcoin`) or you derive it.

> Why do I have to rename this

Name conflicts should be obvious to all programmers?

> `use bitcoin_hashes::sha256::Hash as ThirdHash;`

Yeah, that's why it's better to just import `sha256` module.

Not entirely related: I get the impression that many people tend to import everything but a kitchen sink. I personally prefer to type e.g. `std::error::Error` than worry about possible conflicts. Not saying that my approach is perfect but I guess a bit of inspiration shouldn't hurt. :)

**Comment by TheBlueMatt** [comment]
> Why would you need to manually work with anything from std::hash::Hash? It's either used in data structure (implementation of shouldn't need stuff from bitcoin) or you derive it.

I don't think it should be the position of `bitcoin_hashes` that you should never access `std::hash::Hash`, this seems....unrelated? Sometimes you want to implement your own Hash, or get a u64 that opaquely refers to an object, that's not crazy.

> Name conflicts should be obvious to all programmers?
> Yeah, that's why it's better to just import sha256 module.
> Not entirely related: I get the impression that many people tend to import everything but a kitchen sink. I personally prefer to type e.g. std::error::Error than worry about possible conflicts. Not saying that my approach is perfect but I guess a bit of inspiration shouldn't hurt. :)

Yes, you prefer to operate in one way, other developers operate in other ways, it seems *really* strange that `bitcoin_hashes` is opinionated about how downstream users should handle imports, let alone whether downstream users ever want to use `std::hash::Hash`.

**Comment by Kixunil** [comment]
> I don't think it should be the position of `bitcoin_hashes` that you should never access `std::hash::Hash`

That's not what I meant. I mean it's rare, therefore it's OK if it's a bit annoying. (Or better than large refactorings.)

> `bitcoin_hashes` is opinionated about how downstream users should handle imports

I don't think it is. Rust is specifically designed to handle conflicts well. This is just Rust-idiomatic code. If you rename it to e.g. `digest` (which frankly is less common name in Bitcoin) you risk conflicts with something else called `digest` anyway and there's no global registry of names (and doesn't have to be).

All this being said, I do agree that diagnostics should be improved in Rust and so I filed https://github.com/rust-lang/rust/issues/91059

**Comment by TheBlueMatt** [comment]
> That's not what I meant. I mean it's rare, therefore it's OK if it's a bit annoying. (Or better than large refactorings.)

May not be in every file but I have quite a few places where we use Hash explicitly, its really not that strange. This issue was opened because a downstream (rust-novice) user was confused at hash was returning a u64 even though the docs said it hashes the argument. This really isn't that strange and didn't come out of nowhere.

> I don't think it is. Rust is specifically designed to handle conflicts well. This is just Rust-idiomatic code.

This is the only library I use where literally everything I import from it has the same name. I don't know what libraries you're referring to but I find it... strange that anyone would think a create that exposes an interface built almost entirely out of structs and traits with the same name?!

**Comment by Kixunil** [comment]
Not almost entirely but there are a few cases: `core::result::Result` vs `io::Result`, `io::Error` vs `std::error::Error`, `io::Write` vs `fmt::Write`, `std::path::Path` vs `syn::Path` (OK, these are distinct crates but still...)
I'd say `bitcoin_hashes` is special because it has several similar things but that's also good - it's consistent.

Additional discussion: https://github.com/rust-lang/api-guidelines/discussions/66

**Comment by apoelstra** [comment]
Closing as we are moving to rust-bitcoin and there's been no forward progress on this. I don't want to rename `hash`.

What we probably should do is expose top-level `hash_sha256` etc functions, which in practice should obviate all the need to directly call this crate's `hash` function, as well as being *way* more discoverable, but that's a separate issue.
