### ISSUE TITLE
All-zeroes hash during fuzzing

### ISSUE THREAD

**Issue by uncomputable** [rust-bitcoin/bitcoin_hashes#170]
By design, the hashing during fuzzing is different, which greatly confused me at first _(the holy grail, the hash function, producing unexpected output)_. My problem is that the fuzzer finds inputs that make all my hashes zero, which breaks the compression logic in rust-simplicity. _Basically, we compress everything with the same hash into one._ Is there a way to turn the fuzzing hash function into a cryptographic hash function?

@TheBlueMatt The problem stems from [this code](https://github.com/rust-bitcoin/bitcoin_hashes/blob/master/src/util.rs#L85-L92). I have little experience writing hash engines, so maybe you can take a look at this. If you give me some hints, then I can also try my luck writing a PR.

**Comment by apoelstra** [comment]
@TheBlueMatt I think we already have code that excludes all-0s (since all-0s causes panics in some libsecp functions). But I think we should at least use more than one byte of the hash; maybe 4 bytes instead. That should still easily let the fuzzer find collisions etc while giving us way more room to create large simplicity trees.

What @chlewe wants is that the hash function actually be collision-resistant....unfortunately this might conflict with a design goal here? I'm not sure. I know we want the fuzzer to be able to produce forged signatures but do we need it to be able to produce colliding hashes? If not, we should probably use siphash or something which is very fast but which the fuzzer still won't be able to break.

**Comment by apoelstra** [comment]
What if our hash were to just split the input into 32-byte or 20-byte chunks and then xor these all together? This should allow trivial pre-imaging (at least if the input were smaller than the hash) but still be "collision-resistant" for the sorts of data that Chris and I are using?

> Ah, heh, wasn't aware. I don't see it, though?

Looks like it's actually specific to sha2 lol https://github.com/rust-bitcoin/bitcoin_hashes/blob/master/src/sha256.rs#L131-L133

**Comment by apoelstra** [comment]
@TheBlueMatt yes, collisions are the issue. OP's specific problem (his code is not enforcing sharing, causing fuzztest failures, which then confusingly don't reproduce in `cargo test` without `cfg(fuzzing)`) is something of a red herring. The real issue is that in Simplicity the different parts of our program are content-addressable, and if two program fragments have the same hash, we treat them as identical in all respects: internally they share an `Rc` and when serializing them we only serialize one.

With a broken hash function, we wind up with distinct program fragments which have the same "hash", and which are then "deduplicated" and the program is mangled.

**Comment by chlewe** [comment]
Any two inputs that should produce distinct hashes but actually produce the same hash during fuzzing are a problem, i.e., collisions. In my case, it just happened to be all zeroes, but it could be any constant.

Before effort is wasted, let me update the code on my end. I will try to make fuzzing work by adding a check of the fuzzing input. If the input is already maximally compressed with respect to the hashes, then collisions are no problem. This is how our fuzz tests worked in the past and how I didn't even realise that the hashes are different.

**Comment by apoelstra** [comment]
> If the input is already maximally compressed with respect to the hashes, then collisions are no problem.

Lol. Yeah, I believe this is true. There is the problem that many programs will be unexpressable to the fuzzer, but that's not the end of the world.

Going forward I think we should just find a way to disable `cfg(fuzzing)` for this dependency when fuzzing rust-simplicity.

**Comment by apoelstra** [comment]
Closing in favor of https://github.com/rust-bitcoin/rust-bitcoin/issues/1409 and friends.
