### ISSUE TITLE
Add `hash_again` constructor on `sha256d::Hash`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/bitcoin_hashes#180]
This constructor should accept `sha256::Hash` and create `Self` by hashing the provided value.

Motivation: in `bitcoin` we have this:

```rust
prevouts: sha256d::Hash::from_inner(
    sha256::Hash::hash(&common_cache.prevouts).into_inner(),
),
```

The correctness is not immediately obvious and it caused me to stop and think for a while what's going on. `into_inner()` looked suspicious.

Feel free to suggest a better name.

**Comment by apoelstra** [comment]
I agree. This code does require a double-take (actually, it required reading some comments elsewhere in the module before I was sure it was even intentional), and this `into_inner` `from_inner` business undermines the type system by routing through 32-byte arrays, when we could have `hash_again: sha256::Hash -> sha256d::Hash` which would be simpler and clearer.

**Comment by apoelstra** [comment]
I added it as a method on `sha256::Hash` rather than a constructor on `sha256d::Hash`.
